networks:
  kong-net:

volumes:
  kong-data:
  kafka-data:

services:
  # Broker de mensageria
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
    - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  kafka-create-topics:
    image: apache/kafka:4.1.1
    container_name: init-kafka-topics
    depends_on:
      kafka:
        condition: service_healthy
    command: /opt/kafka/bin/kafka-topics.sh --create --topic notification-v1 --partitions 3 --bootstrap-server kafka:9092
    restart: no

  # Banco de dados
  postgres:
    image: postgres:15-alpine
    container_name: kong-postgres
    networks:
      - kong-net
    volumes:
      - kong-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Migração do banco (roda 1 vez e para)
  kong-migration:
    image: kong:3.7
    container_name: kong-migration
    networks:
      - kong-net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    restart: on-failure

  # Kong Gateway
  kong:
    image: kong:3.7
    container_name: kong
    networks:
      - kong-net
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # Proxy HTTP
      - "8001:8001"  # Admin API
      - "8002:8002"  # Admin GUI
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microserviço de Agendamento
  appointment-ms:
    build:
      dockerfile: Dockerfile
      args:
        SERVICE: appointment-ms
    container_name: appointment-ms
    networks:
      - kong-net
    ports:
      - "3001:8080"
    #  - "3001-3002:8080"
    restart: unless-stopped
    #deploy:
    #  mode: replicated
    #  replicas: 2
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # Microserviço de Notificação
  notification-ms:
    build:
      dockerfile: Dockerfile
      args:
        SERVICE: notification-ms
    container_name: notification-ms
    networks:
      - kong-net
    ports:
      - "3003:8080"
    restart: unless-stopped
    depends_on:
      kafka:
          condition: service_healthy