spring:
  kafka:
    topic:
      name: "appointments-events"
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: appointment-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.fiap.core.message.AppointmentMessage
        spring.json.use.type.headers: false
      enable-auto-commit: false
    listener:
      ack-mode: manual
  mail:
    host: smtp.gmail.com
    port: 587
    username: fiaptech26@gmail.com
    password: tdyd asep pgvx obqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
